import { t } from "i18next";
const categoryList = [
  t("accounting"),
  t("admin"),
  t("advert"),
  t("agri"),
  t("arch"),
  t("auto"),
  t("banking"),
  t("business"),
  t("busin"),
  t("comm"),
  t("commun"),
  t("consult"),
  t("creative"),
  t("customer"),

  t("development"),
  t("eco"),
  t("edu"),
  t("eng"),
  t("environment"),
  t("health"),
  t("hotel"),
  t("human"),
  t("info"),
  t("language"),
  t("legal"),
  t("logistic"),
  t("maintenance"),

  t("managment"),
  t("manu"),
  t("media"),
  t("natural"),
  t("pharma"),
  t("purchasing"),
  t("quality"),
  t("research"),
  t("retail"),
  t("sales"),

  t("science"),
  t("security"),
  t("social"),
  t("strategic"),
  t("tele"),
];
const languageList = [
  { language: "Afar", code: "aa" },
  { language: "Amharic", code: "am" },
  { language: "Arabic", code: "ar" },
  { language: "Danish", code: "da" },
  { language: "German", code: "de" },
  { language: "English", code: "en" },
  { language: "Spanish", code: "es" },
  { language: "French", code: "fr" },
  { language: "Italian", code: "it" },
  { language: "Portuguese", code: "pt" },
  { language: "Russian", code: "ru" },
  { language: "Somalia", code: "so" },
  { language: "Tigrinya", code: "ti" },
  { language: "Turkish", code: "tr" },
  { language: "Chinese", code: "zh" },
];
const regionsList = [
  t("addis"),
  t("afar"),
  t("amhara"),
  t("bengu"),
  t("dire"),
  t("gambela"),
  t("harer"),
  t("oro"),
  t("sida"),
  t("soma"),
  t("south"),
  t("tigray"),
  t("southern"),
];
export { categoryList, languageList, regionsList };
